###
# Welcome to the new js2coffee 2.0, now
# rewritten to use the esprima parser.
# try it out!
###
console.log '1111111111111111111111111111111111'

listen = (el, event, handler) ->
  if el.addEventListener
    el.addEventListener event, handler
  else
    el.attachEvent 'on' + event, ->
      handler.call el

window.onload = ->
  app.init()
  console.log '123'
  console.log '456'
  console.log '789'
  return




# ---
# generated by js2coffee 2.2.0